/**
 *! __THIS CODE WAS AUTOGENERATED__
 *? FOR: handling uncaught exceptions.
 */
process.on("uncaughtException", (err) => {
  console.error(
    `Uncaught exception: ${err.name} ${err.message}, ${err.stack} , shutting down...`
  );
  process.exit(1);
});

/**
 *? Configure .env files
 */
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "/config/.env") });

const App = require("./api/app");

const PORT = process.env.PORT || 3000;
const server = App.listen(PORT, () =>
  console.log(`Server listening at Port ${PORT}...`)
);

/**
 *! __THIS CODE WAS AUTOGENERATED__
 *? FOR: handling unhandled rejections.
 */
process.on("unhandledRejection", (err) => {
  console.error(
    `Unhandled Rejection: ${err.name} ${err.message} , shutting down...`
  );
  server.close(() => {
    process.exit(1);
  });
});
